---
kind: Service
apiVersion: v1
metadata:
  name: api-demo-service # Service name
  labels:
    app: api-demo
spec:
  type: LoadBalancer
  selector:
    app: api-demo # Label selector. The Service targets Pods that use this label
  ports:
    - port: 80 # Port used to access the Service from within the cluster.
      targetPort: 3030 # Port opened by targeted Pods